### ISSUE TITLE
Household screening: the hints should be flagged as a message when no or non is selected respectively

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#107]
Change the radiobuttons to checkboxes. 
Add tghe option "none" and if none is selected no other options should be selectable
When the option "other" is selected a field in which the user should enter that other option should appear.
![Screenshot_20210903-162916_Ecap II](https://user-images.githubusercontent.com/25362528/132022944-5f846ad3-dd48-4990-833a-fd19431dad98.jpg)

**Comment by gladysyabs** [comment]
The options on HIV prevention methods should be a checklist
