### ISSUE TITLE
CasePlan 

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#115]
The field physical address on the case plan is supposed to have pre populated information. The field is not clickable 
![Screenshot_20210909-204141_Ecap II (1)](https://user-images.githubusercontent.com/86519642/132757396-8a1f603a-f0bd-4843-8a41-fb91c340823d.jpg)

**Comment by tobiasmakai** [comment]
Closed because issue was not assigned to anyone, not even on the project board.
