### ISSUE TITLE
Household screening form: wrong age being captured on the pre  filled field

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#118]
The age been captured is not correct, e.g i entered the year of birth 2005 , it is giving me the age ass 13 instead of 16 years.
![Screenshot_20210909-224914_Ecap II](https://user-images.githubusercontent.com/86519642/132761126-ccf44353-10ee-4f01-b7d3-6fbf31d3fb2c.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
