### ISSUE TITLE
Household screening form: Wrong pre populated information

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#119]
The information that am getting after adding a person is wrong, the person created  was Bernard but once i click on Bernard and try to add the household screening form am getting details of Maimbo Tembo and the age of maimbo tembo which i didnt enter
![Screenshot_20210909-225636_Ecap II (1)](https://user-images.githubusercontent.com/86519642/132762197-e7422269-4685-48fa-b8ff-21cd51e25329.jpg)

**Comment by Yosefe27** [comment]
@gladysyabs I have tested this issue and everything seems fine so far, I will go ahead and move it to completed, you can confirm if the problem is still existent and it can me moved back.
