### ISSUE TITLE
Index VCA Screening Form

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#145]
Under C/ALHIV, a question remains on nutrition even when you click on child 
not HIV+.

**Comment by chobela** [comment]
Hi @gladysyabs I need confirmation on this. Is this as per client requirement? coz that is not stated in the form.

**Comment by gladysyabs** [comment]
Hi @chobela  so this issue, if a child is below 2 years and HIV +, the question on nutrition does not need to show under C/ALHIV.

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
