### ISSUE TITLE
Index VCA Screening Form: Check in the data dictionary - If ‘no’ to question on access to clinical services, the services should not show (skip logic)

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#146]
If ‘no’ to question on access to clinical services, the services should not show 
(skip logic)
![Screenshot_20210916-215738_Ecap II](https://user-images.githubusercontent.com/86519642/133678141-80c7f7bd-9332-4010-ac76-a8c1d3cfd044.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
