### ISSUE TITLE
Index VCA Screening Form - If below 5 years old, question on school should disappear or add N/A action.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#147]
If below 5 years old, question on school should disappear or add N/A action. 
But this point might require further discussion.
![Screenshot_20210916-215738_Ecap II (1)](https://user-images.githubusercontent.com/86519642/133678912-03c7a18a-40c7-4b11-97e3-4c1617d9a131.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
