### ISSUE TITLE
Index VCA Screening Form:Is Mother currently on treatment? is mother adhering to treatment? ART number, Is mother virally suppressed?, are being repeated under C of WLHIV even when they were already answered in HEI...so basically some sections are being repeated even if they are already answered in another section.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#149]
![Screenshot_20210916-221839_Ecap II](https://user-images.githubusercontent.com/86519642/133680533-4c99d886-a161-46f8-8c78-7acb3442ff54.jpg)
![Screenshot_20210916-221943_Ecap II](https://user-images.githubusercontent.com/86519642/133680619-1412cb1d-6d47-4ace-8fe1-578057a15081.jpg)

**Comment by gladysyabs** [comment]
The questions are still being repeated

**Comment by chobela** [comment]
We have a challenge on this issue. The Sub Pops do not depend on each other. So the C/WHIV Questions and the HEI Questions can only be asked in their respective subpops. C/WHIV Questions cannot depend on HEI Questions.

**Comment by Yosefe27** [comment]
@gladysyabs what is the way forward with this issue?
