### ISSUE TITLE
Index VCA Screening Form: Question D.10, D.11 and D.12 was skipped.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#150]
Question D.10, D.11 and D.12 was skipped.
![Screenshot_20210916-223328_Office](https://user-images.githubusercontent.com/86519642/133682420-55e3d394-68da-4d7a-9ed3-b90a1fd157a9.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
