### ISSUE TITLE
Index VCA Screening Question 5C should not be there on C/ALHIV

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#151]
Question C5 should not be there on C/ALHIV
![Screenshot_20210916-224049_Office](https://user-images.githubusercontent.com/86519642/133683168-85f75b3f-de2c-4b84-872a-ec0d665f0156.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
