### ISSUE TITLE
HH Screening Form - No heading on HIV status.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#157]
No heading on HIV status.
![Screenshot_20210916-233121_Ecap II](https://user-images.githubusercontent.com/86519642/133688746-7635b0f7-8f16-4e8e-a6ec-f0732cb64710.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
