### ISSUE TITLE
HH Screening Form -Skip logic on relationship to primary caregiver and sex e.g. for male, all female ‘relationship’ should be unhighlighted.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#158]
Skip logic on relationship to primary caregiver and sex e.g. for male, all 
female ‘relationship’ should be unhighlighted. 
![Screenshot_20210916-234159_Ecap II](https://user-images.githubusercontent.com/86519642/133689784-c4a1cdd2-ff7a-46f2-80bc-b4552f9a9400.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
