### ISSUE TITLE
HH Screening Form -D16 should have a N/A if index is HEI.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#159]
D16 should have a N/A if index is HEI.
![Screenshot_20210917-000112_Office](https://user-images.githubusercontent.com/86519642/133691597-c4692f22-6a9e-4fda-b3fe-5992df375e26.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
