### ISSUE TITLE
HH Screening Form -If ‘yes’ to question, ‘did the AGYW test positive to HIV, then AGYW should be pulled to C/ALHIV and questions for positives should appear

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#162]
If ‘yes’ to question, ‘did the AGYW test positive to HIV, then AGYW should be 
pulled to C/ALHIV and questions for positives should appear
![Screenshot_20210917-001705_Ecap II](https://user-images.githubusercontent.com/86519642/133692958-7f5fbb0f-2eab-4d43-bda0-b98b118531b9.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
