### ISSUE TITLE
HH Screening Form:Specify ‘other’ under the question on pregnancy prevention. When other is selected there is need for a text box to specify other methods being used.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#163]
![Screenshot_20210917-001945_Ecap II](https://user-images.githubusercontent.com/86519642/133693333-17ccb1c8-9daf-48fe-a8f1-df6115b63dd5.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
