### ISSUE TITLE
Enrollment Form - Could not read anything under nutrition assessment for under-5 children. the fields are not active

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#168]
Could not read anything under nutrition assessment for under-5 children.
oThe fields are not active
![Screenshot_20210917-004307_Ecap II](https://user-images.githubusercontent.com/86519642/133695025-23bbb7dd-7e73-4c75-87d7-711dab9b8108.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
