### ISSUE TITLE
VCA profile should pull age and not date of birth or null.

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#175]
![Screenshot_20210919-231933_Ecap II](https://user-images.githubusercontent.com/25362528/133943414-e4df61f1-11f0-4175-a640-49d298793c80.jpg)

**Comment by gladysyabs** [comment]
VCA age on the profile is showing not set.
![Screenshot_20211006-123653_Ecap II](https://user-images.githubusercontent.com/86519642/136187874-de5d99d6-a27c-4da4-8ab0-0ced1412d990.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
