### ISSUE TITLE
Age of VCA showing not set instead of age

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#196]
Age of VCA should be pre-populated if it has been entered already on household screening form

**Comment by gladysyabs** [comment]
Age of the VCA on household screening is showing not set instead of the age.
![Screenshot_20211006-124152_Ecap II](https://user-images.githubusercontent.com/86519642/136188448-014f9d37-c13e-456f-9407-385a93592e33.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
