### ISSUE TITLE
relationship to caregiver

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#201]
In the dropdown list include Son and Daughter
![Screenshot_20211001-131550_Ecap II (1)](https://user-images.githubusercontent.com/86519642/135611437-caee96fc-2cf4-4a10-94a2-db81342f64ba.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
