### ISSUE TITLE
Service Report

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#205]
Isn't the household also suppose to show the services being offered?
![Screenshot_20211001-160653_Ecap II](https://user-images.githubusercontent.com/86519642/135634382-8e68c3b8-fdb3-4d56-ac0d-c9cedf130550.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
