### ISSUE TITLE
ART field validation on OVC form does not match keyboard response. No hyphen on keyboard.

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#206]
![Screenshot_20211001-213350_Ecap II](https://user-images.githubusercontent.com/25362528/135677053-9ace5d6c-3d81-45d1-979b-d6cdeea8b6c1.jpg)

**Comment by gladysyabs** [comment]
The keyboard on ART for C/ALHIV is still showing numbers
