### ISSUE TITLE
OVC Register: "Next VL Result" field should not be active before the date entered in  "Date of Next VL"

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#207]
![Screenshot_20211001-214226_Ecap II](https://user-images.githubusercontent.com/25362528/135678235-8b4e5f16-ba1b-4d02-958e-d047e53a606c.jpg)

**Comment by chobela** [comment]
This issue will not be required because "VL Next Results" was advised to be removed
