### ISSUE TITLE
Caregiver name to be uniform on all the forms.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#218]
The format for the name of  the caregiver should be uniform on all the forms. Lets decide which format we will use if its Caregiver Name or Caregiver First and Last name. 
![Screenshot_20211004-154128_Ecap II (1)](https://user-images.githubusercontent.com/86519642/135862877-1be097f8-ec16-4aa1-857a-3c3d53a5387b.jpg)
![Screenshot_20211004-153702_Ecap II](https://user-images.githubusercontent.com/86519642/135862914-e349d89d-ed0b-460a-9ad6-71274f21643f.jpg)

**Comment by Yosefe27** [comment]
It has been agreed that we will use Full Name for the caregiver instead of First Name and Last Name. This will be changed on all forms where change needs to be made.

**Comment by gladysyabs** [comment]
Name of caregiver should be uniform in all the forms.
