### ISSUE TITLE
Age still not being picked on HH 

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#219]
The age is still not being picked on household screening form.
![Screenshot_20211004-160046_Ecap II](https://user-images.githubusercontent.com/86519642/135865382-c2feb916-4571-4c0b-92cb-d5c6b5119f64.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
