### ISSUE TITLE
VCA assessment - On the question was HIV test done less than 6 months ago? If no is selected its to assess for HIV risk and if Yes is selected then it goes to the next question.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#226]
![Screenshot_20211005-153121_Ecap II](https://user-images.githubusercontent.com/86519642/136035809-5d1422cf-9a1c-42d8-862b-0cf898af8483.jpg)

**Comment by tobiasmakai** [comment]
The next question on tatoos is still on the list of questions despite shoosing no

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
