### ISSUE TITLE
vca case plan - C/ALHIV

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#227]
C/ALHIV should be Yes or No. At the moment it's not clickable
![Screenshot_20211005-155840_Ecap II](https://user-images.githubusercontent.com/86519642/136038446-f8b90589-f181-4bc3-b54e-39c21ece2adc.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
