### ISSUE TITLE
On subpop its picking a wrong subpop that was not selected.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#235]
On subpop its picking a wrong subpop that was not selected. Example VCA captured as C/ALHIV, Children of WLHIV is correct but the last one ticked Children of FSW is not correct.
![Screenshot_20211006-124527_Ecap II (1)](https://user-images.githubusercontent.com/86519642/136189336-c40b2cdd-1bf5-48ef-82e4-78596f6b99ae.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
