### ISSUE TITLE
Name of assigned community case worker is not being picked.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#236]
The name of the Community assigned case worker is not being picked.
![Screenshot_20211006-125400_Ecap II (1)](https://user-images.githubusercontent.com/86519642/136190176-12948e9d-e021-4856-ac60-69b5aa7a9e33.jpg)

**Comment by Yosefe27** [comment]
@gladysyabs @chobela Stale issue, moved to completed.
