### ISSUE TITLE
Agree on one format for the name of assigned case worker to be used on all the forms.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#237]
Format for the name of assigned case worker should be uniform on all the forms where it is appearing.

**Comment by Yosefe27** [comment]
It has been agreed that we will use Full Name for the Assigned Case Worker instead of First Name and Last Name. This will be changed on all forms where change needs to be made.

**Comment by gladysyabs** [comment]
This issue is still pending
