### ISSUE TITLE
The name of implementing partner, date of screening, telephone and Location  is not being picked on HH screening

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#238]
The name of implementing partner, date of screening and telephone is not being picked.
![Screenshot_20211006-130407_Ecap II](https://user-images.githubusercontent.com/86519642/136191309-49dcf675-a983-45e7-8a66-b0027237cabf.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
