### ISSUE TITLE
The format size for the field relationship of Household  member to primary caregiver should reduce 

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#239]
The format size for the field relationship of Household 
![Screenshot_20211006-154148_Ecap II (1)](https://user-images.githubusercontent.com/86519642/136218174-ccb31351-8a37-4925-9d41-3d05f68c0919.jpg)
member to primary caregiver should reduce so that it fits on the screen, It should be similar to the one on  household summary information 2  
![Screenshot_20211006-154249_Ecap II (1)](https://user-images.githubusercontent.com/86519642/136218365-5e0bfaff-1524-49ef-a279-76a75cc53c05.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
