### ISSUE TITLE
The Question on did AGYW answer yes to any of the above question should be categorize as AGYW at risk. This only applies to DII.I to Dll.10

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#240]
The question on did AGYW answer yes to any of the above questions, only apply to question DI which is ( Is the AGYW 10-17 years)  to DI0 which is (Has the AGYW ever been diagnosed with a Sexually Transmitted Illness (STI)?). If the answer is Yes to any of those questions that's when you categorize AGYW at risk so this excludes the fields below D10. Refer to household screening tool.
![Screenshot_20211006-162146_Ecap II](https://user-images.githubusercontent.com/86519642/136224584-eb83ff52-b84d-4269-b693-b362969f90f9.jpg)

**Comment by gladysyabs** [comment]
The question did AGYW answer to any of the questions from part D.2 above will include yes to even questions like school

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
