### ISSUE TITLE
After entering information on HH screening form and approving enrollment. The HH screening starts again with  prefilled information.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#242]
After entering information on HH screening form and approving enrollment. The HH screening starts again with  prefilled information. Is this supposed to be there?
![Screenshot_20211006-165226_Ecap II](https://user-images.githubusercontent.com/86519642/136229047-83f281e2-abc5-40ce-a2b0-3b6bb9bb0e41.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
