### ISSUE TITLE
Only ‘Other HH Members’ should be actively entered HH summary form 

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#254]
![Screenshot_20211008-114944_Ecap II](https://user-images.githubusercontent.com/86519642/136536278-52bdc8a4-55f7-4bd7-b540-be31e3c8fd2d.jpg)and not include having to re-enter the CG and Index VCA information all over again.

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
