### ISSUE TITLE
Facility should have a drop down menu.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#255]
Facility should have a drop down menu showing the list of facilities in that district.
![Screenshot_20211008-115440_Ecap II](https://user-images.githubusercontent.com/86519642/136536934-87149e1b-295e-4114-9673-64b5f8587a75.jpg)

**Comment by tobiasmakai** [comment]
@chobela you can find the list of facilities here

https://docs.google.com/spreadsheets/d/1aoawNuF4xgtmz51Lo6N5S-Wa4lMSd42i/edit#gid=1021069673

**Comment by chobela** [comment]
This is no longer necessary because it was agreed that the facility will populate based on the Case workers' facility
