### ISSUE TITLE
Can AGYW questions come during the summary form

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#257]
Can AGYW questions come during the summary form when the info entered shows that it’s a female 10-17 years? Or have the names pre-populated so that they are not entered again.

**Comment by chobela** [comment]
@gladysyabs Which one is the Summary form?

**Comment by Yosefe27** [comment]
@gladysyabs @chobela this issue is stale and maybe closed, the fields were in repeating groups which have been moved to separate forms. Kindly review.  I have since moved it to completed.
