### ISSUE TITLE
Add ‘type of referral’ to the Index VCA or Index Mother form

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#259]
Add ‘type of referral’ to the Index VCA or Index Mother form. This should come at the very beginning of index VCA or Index Mother Form
![Screenshot_20211019-140300_Ecap II (1)](https://user-images.githubusercontent.com/86519642/137906185-c27ce91e-1932-49c9-be4f-3fe6daddc94a.jpg)

**Comment by Yosefe27** [comment]
@gladysyabs Kindly shed more light on this issue.

**Comment by chobela** [comment]
Type of referral is automatic in the system. Thats why it was marked as completed
