### ISSUE TITLE
Investigate the consent error that is causing the app to crush

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#282]
Scenario: On sub-pop form create a child to be both C/ALHIV and CWLHIV. Tap Yes on all questions under C/ALHIV and also enter ART number. Answer Yes on all questions under CWLHIV enter Mother's ART Number. Answer No to the questions "...experienced sexual violence" and "is child caregiver an FSW".

**Comment by chobela** [comment]
@tobiasmakai Kindly recreate the above option when u test the build.
![Screenshot from 2021-10-20 10-38-49](https://user-images.githubusercontent.com/16720694/138058940-1e2b6f6a-82b9-4d67-8044-be442a5cc804.png)

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
