### ISSUE TITLE
HH screening: number of AGYWs in household cannot be more than the number of household members

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#290]
![Screenshot_20211014-202452_Ecap II](https://user-images.githubusercontent.com/25362528/137374749-4cef04dd-fabc-419d-8187-806ce6d82d22.jpg)

**Comment by Yosefe27** [comment]
This issue has been taken care of with the removal of repeating groups.

**Comment by gladysyabs** [comment]
The number of AGYW in the household cannot be more than the number of household members

**Comment by Yosefe27** [comment]
@tobiasmakai @gladysyabs Kindly close this issue as we have changed the way this information is display and this issue no longer applies. I have since moved it to completed.
