### ISSUE TITLE
HH screening part E: Question on VL suppressed cannot be yes if is VL below 1000 or VL cannot be less than 1000 if yes is selected to the VL question

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#296]
![Screenshot_20211014-212715_Ecap II](https://user-images.githubusercontent.com/25362528/137383185-6f7cc82b-f403-4ac8-9c80-c246e6202603.jpg)

**Comment by tobiasmakai** [comment]
Interchange the order of the questions to have the VL result field come before the VL suppressed field. If the VL result field not filled the suppressed question should not appear.

**Comment by chobela** [comment]
The VL Suppressed question will not be necessary in the system because it is an "Either / Or" Question. The VL Can only be above or below 1000. So during Querries of the DB, Those below 1000 will be classified as suppressed, and those above 1000 will be  "Not suppressed."

**Comment by tobiasmakai** [comment]
1000 and above - Not suppressed.
