### ISSUE TITLE
HH screening: pre-populate details based on already recorded members of the HH that fall in the AGYW category

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#303]
![Screenshot_20211014-235815_Ecap II](https://user-images.githubusercontent.com/25362528/137401521-792f1b37-ef27-405d-b440-722121fb9da7.jpg)

**Comment by Yosefe27** [comment]
@tobiasmakai @chobela stale issue relating to repeating groups. Moved to completed.
