### ISSUE TITLE
HH enrolment: HH summary information should be pre-populated from HH screening

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#304]
![Screenshot_20211015-000943_Ecap II](https://user-images.githubusercontent.com/25362528/137402525-649a12b4-3d22-4a00-b99d-2b8cd0e9f52a.jpg)
![Screenshot_20211015-001955_Ecap II](https://user-images.githubusercontent.com/25362528/137403396-19c958ed-d0b6-458d-94fd-61fb5064c601.jpg)
![Screenshot_20211015-002501_Ecap II](https://user-images.githubusercontent.com/25362528/137403864-24b38660-e4c7-4748-8266-960dfd67a9db.jpg)

**Comment by Yosefe27** [comment]
@tobiasmakai @chobela These fields have been removed from this form, issue moved to completed.
