### ISSUE TITLE
VCA assessment: any reason why the two labels are in bold font unlike the rest?

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#316]
![Screenshot_20211015-135419_Ecap II](https://user-images.githubusercontent.com/25362528/137482904-7bf8dbeb-4c15-4e16-9f0a-6c937f0eeeb1.jpg)

**Comment by gladysyabs** [comment]
Am not seeing this question on the latest APK

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
