### ISSUE TITLE
Maintain the same font size on relationship to primary caregiver.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#331]
![Screenshot_20211020-235905_Ecap II](https://user-images.githubusercontent.com/86519642/138178631-fabe1e15-85ec-41b5-a47a-49b850dc2ee1.jpg)
![Screenshot_20211020-235811_Ecap II](https://user-images.githubusercontent.com/86519642/138178635-a1233a0b-4c64-41d7-a13d-00da0e617f9b.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs Close issue if done

**Comment by gladysyabs** [comment]
Okay will do that

**Comment by gladysyabs** [comment]
okay doing that
