### ISSUE TITLE
This issue needs to be looked into, after completing the HH screening form , the form starts again after approval.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#334]
Check the attached screen. It starts below the list of recommended services
![Screenshot_20211027-110939_Ecap II](https://user-images.githubusercontent.com/86519642/139044578-cb6d4d4b-8323-4cec-84ae-7d51c198706a.jpg)
shoot

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
