### ISSUE TITLE
The information VCA house Id, primary caregiver first name, primary caregiver last name, caregiver d.o.b, caregiver gender. This information has to be prepopulated

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#349]
Remember you have already captured this information, so one does not need to start re-entering the same information.
![Screenshot_20211120-163513_Ecap II](https://user-images.githubusercontent.com/86519642/142730389-73610ea9-3afa-4766-801c-fc09c07bf7ce.jpg)

**Comment by tobiasmakai** [comment]
"Caregiver gender" still not pre-filling on HH assessment form despite being already captured

**Comment by tobiasmakai** [comment]
HIV Status is not pre-filling

**Comment by tobiasmakai** [comment]
HIV Status is not pre-filling
