### ISSUE TITLE
ART Number format for all the ART# fields should be XXXX-XXXXX-XXXXXX-X

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#360]
4 digits - 5 digits - 6 digits - 1 digit

**Comment by tobiasmakai** [comment]
New information is that the format should be; 4 digits - 3 or 4 digits - 5 or 6 digits - 1 digit

**Comment by gladysyabs** [comment]
The ART should be in that format. The second role after the dash should have 5 digits
![Screenshot_20220105-123841_Ecap II](https://user-images.githubusercontent.com/86519642/148204376-f996ce29-5b88-46aa-8cea-9120ee6869e9.jpg)
