### ISSUE TITLE
The field "Is the child currently on ART" should be ticked "yes" if the VCA is HIV positive and already on ART and No if the VCA is HIV positive but not on ART.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#377]
![Screenshot_20211130-204819_Ecap II (1)](https://user-images.githubusercontent.com/86519642/144111070-2e60c2d6-8c8b-46e1-8e38-e888cc377aa4.jpg)

**Comment by chobela** [comment]
Kindly provide more clarity on this issue. Its not clear. - Chobela

**Comment by gladysyabs** [comment]
It seems this issue has been worked on already. So if a user selects no on the question "Is the child/Adolescent currently on HIV treatment?"  then on the question "Is child on ART" this should be already prefilled No. Cause we have said no to treatment. This applies to when yes is also selected.
