### ISSUE TITLE
Additional of new fields on TB for an HIV+ VCA. This questions should come immediately below the question "Does the child/adolescent have their TB screening results on file?"

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#443]
The following additional should show for an HIV + VCA when identifying the subpopulation which the Index will belong.
1. Was the client screened for TB during the last clinical visit
a. Yes
b. No
2. If the answer to question 1 is Yes, what was the screening
result.
a. Negative
b. Positive
3. If the answer is Negative, was client eligible for TPT
a. Yes
b. No
4. If the answer to question 3 is yes, was the client initiated
on TPT
a. Yes
b. NO

**Comment by tobiasmakai** [comment]
High priority addition
