### ISSUE TITLE
Enrolment into OVC program: implement the following validations and skip logic on the following fields

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#464]
- [x] "Date referred", "Date offered enrollment", "Do you accept the offer of enrollment" should be required fields.
- [x] If "No" is selected under the field "Do you accept the offer of enrollment" the form should be aborted (user cannot proceed further and should redirected to the VCA register). Think about how such VCA will be saved i.e. a distinction between enrolled and not enrolled VCAs in the register.
- [x] The field "Date enrolled" and the rest of the fields that come after it should only appear or be active if "Yes" is selected under the field "Do you accept the offer of enrollment".
- [x] "Date enrolled" should be a required field if the above criteria is met.
- [x] "Date HIV Status was known" should be a required field and a tooltip/information tip "Give an estimate if the exact date is not known" should appear immediately the field is active.
- [x] "Date Started ART" should only be active or appear if "Yes" is selected under the field "Is the child currently on ART?"
- [x] "Date Started ART" should be a required field if the above criteria is met and a tooltip/information tip "Give an estimate if the exact date is not known" should appear immediately the field is active.
- [x] "Is the child eligible for VL test?" should be a required field.
- [x] The fields "Date of last VL test" and "Last VL results" should only appear or be active if "Yes" is selected under the field "Is child eligible for VL test?". The fields should be optional (not required)
- [x] "Is Child VL suppressed? (less than 1000 copies/ml)" should only appear or be active if the field "Last VL results" has been filled in with data and can only be "Yes" or "No" based on the VL results provided i.e. less than 1000 is "Yes" (VL suppressed) while 1000 and above is "No" (Not VL suppressed).
- [x] "Is the child on MMD?" should only appear or be active if "Yes" is selected under the field "Is the child currently on ART?"
- [x] "Level of MMD for child" should only appear of be active if "Yes" is selected under the field "Is the child on MMD?"
- [x] Flag appropriate errors where they are needed.

**Comment by gladysyabs** [comment]
@chobela @josephtj @Davidju97 @Yosefe27 Am taking this issue back to do, ensure the validations and skip logic is re-looked into. For the field VL result allow the user to enter the VL result based on the result that is provided if the User providers a value that is below below 1000 copies the next question should be ticked No and if the user enters a VL result that is more than 1000 copies. The next field should indicate Yes.

**Comment by gladysyabs** [comment]
@tobiasmakai okay noted
