### ISSUE TITLE
Consent: if there is a "Yes" there should be a "No".

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#477]
Selecting "No" should redirect to the the VCA register. VCA's record should still be saved. Find a way of showing those who didnt consent (VCAs pending consent).
![Screenshot_20220113-103225_Ecap II](https://user-images.githubusercontent.com/25362528/149295142-57699212-6959-45db-b1e7-39118ebc9f2d.jpg)

**Comment by Yosefe27** [comment]
@tobiasmakai If the users chooses "No", should the process end here and should the user be able to save the already captured information or should the record be disregarded altogether? Or should we provide a field for a reason for "Not Consenting"?

**Comment by tobiasmakai** [comment]
@Yosefe27 data should be saved but we have to provide a mechanism of showing VCAs pending consent.
