### ISSUE TITLE
The field "VL result"  on vulnerability assessment should be a drop down list with the following options "Less than 1000 copies/ml" and "More than 1000 copies/ml" .

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#586]
![Screenshot_20220202-222255_Ecap II](https://user-images.githubusercontent.com/86519642/152233596-1a27dc06-a82e-42b2-9d8c-c39ce6c1efe7.jpg)

**Comment by tobiasmakai** [comment]
@gladysyabs Was this the feedback from the client?

**Comment by chobela** [comment]
We need more clarity on this issue
