### ISSUE TITLE
Drop the Organization initials in the ID. Just have the field for Partner Organization on both the entry point forms (i.e. Mother index, FSW and VCA Index forms) and HH screening.

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#595]
This is because the Case worker who may have entered the information of the Index VCA can in many cases be different from the one who goes to the household to screen. E.g. A case worker from COH screens a VCA and the Case Worker from BISO screens a Household for that VCA.

**Comment by Yosefe27** [comment]
@tobiasmakai Kindly shed more light on this issue

**Comment by tobiasmakai** [comment]
@Yosefe27 kindly read issus #54 first especially reference to the Partner code is made then get back to this issue. Let me know where i need to clarify after that.
