### ISSUE TITLE
Correct how the keyboard responds to the fields in VCA Case Plan.

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#643]
![Screenshot_20220216-201155_Ecap II](https://user-images.githubusercontent.com/25362528/154331159-375355d0-6ee2-4df6-8a40-9ed0119927c3.jpg)

**Comment by Yosefe27** [comment]
@tobiasmakai Kindly advise what exactly the issue should resolve, I have tested the fields and everything seems fine except for a misspelling on required field.

**Comment by tobiasmakai** [comment]
Issue is on how the fields trigger the keyboard when active (lower/upper case). @chobela please explain.

**Comment by Yosefe27** [comment]
@tobiasmakai Oh I have understood what you are referring to with this issue, I think I was just tired. I have corrected it. @chobela
