### ISSUE TITLE
Ensure that feature "Household visitation" 20 years+ is disabled in the next build. We are going to confuse the user who will want to click on it .

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#646]
![Screenshot_20220217-085859_Ecap II](https://user-images.githubusercontent.com/86519642/154422808-de3d9297-912c-4676-8978-8ceb7b0383dd.jpg)

**Comment by Yosefe27** [comment]
@tobiasmakai @gladysyabs should this feature remain disabled?
