### ISSUE TITLE
Feedback received from deployment that has to be worked on. I will be updating this list. 

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#672]
### Index VCA screening

- [x] If the index VCA is categorized as C/ALHIV, the subpopulation AGYW should not be active. This applies to an Index VCA below the age of 10 years. The AGYW should not be active 
- [x] On the subpopulation Children of Female Sex Workers (FSWs), the fields “Is the Child/Adolescent receiving any age-appropriate HIV and sexual violence prevention intervention?” and “ Is the Adolescent and Caregiver receiving any economic strengthening intervention?” were not included
- [x] If the VL result is less than 1000 copies then the VL result is suppressed and if the VL result is suppressed then the Date of next VL test should be 1 year from the Date of last VL test but if the VL result is above 1000 copies then the VL result is unsuppressed. if the VL result is unsuppressed then the Date of next VL test should be 3 months from the Date of last VL test 
- [x] The field “Screening Location” has not been captured on Index VCA screening.
- [x] Some questions are missing on the subpopulation Children/Adolescents whose Primary Caregivers are HIV Female Sex Workers (FSWs).https://docs.google.com/document/d/1a0egFdVp6u_2-0Km4ShsM9ILpVi55I4U/edit
- [x] Change the question ``Was eligible for TPT to “was client initiated for TB Preventive Therapy? (TPT)”
- [x] Change the question ``Was client initiated for TPT to “was client initiated for TB Preventive Therapy? (TPT)”.
- [x] On the phone number field, Is it possible to allow a user to enter a  Telephone number?.
- [x] Ensure when a user edits the subpopulation. For example if the user said "Yes" to Children of FSW. Then later changes this information to "No" on children of FSW. The details on the VCA profile on Subpopulation should also be updated
- [x] On the subpopulation  "Children/Adolescents whose primary caregivers are HIV Female Sex Workers (FSWs)" Remove the question "Is the child/adolescent in school". This information has been captured on social demographic information.

### VCA Screening

- [x] Ensure all the fields “Has the child/adolescent been tested for HIV?” and  “Is the Adolescent and caregiver receiving any economic strengthening intervention? "on the subpopulation  children /adolescents whose primary caregivers are HIV Female Sex Workers (FSWs)  are prefilling, If this information has already been captured on Index VCA screening

### Household  screening and Enrollment

- [x] When a user starts entering information using the household screening, the added VCA is showing a gray line and opening a wrong profile. I have recreated this issue so for now when caseworkers are entering information from their files to the application. They should not start with screening and it will pick all the subpopulations event those that have not been selected.
- [x] If the VL result is less than 1000 copies then the VL result is suppressed and if the VL result is suppressed the question “ Are you virally suppressed as of your most recent Viral load test? Should be ticked ``Yes” and If the VL result is above 1000 copies then the VL result is unsuppressed and if the VL result is unsuppressed the question “ Are you virally suppressed as of your most recent Viral load test? Should be ticked No”.  if it is No is ticked on “Are you virally suppressed as of your most recent Viral load test?” then show a message toast “Refer and provide appropriate care and support support services”. So the order should be “Date of last VL test” then “VL result” and lastly “Are you virally suppressed as of your most recent Viral load test? ”
- [x] Ensure the fields are consistent in all features. E.g  On Index screening the label Home Address has been labeled “Address” on Household screening.
- [x] Ensure household field is prefilled, if the information has been provided when conducting Index VCA screening.
- [x] On household enrollment if the Marital status “Married or Not married, In a relationship” is selected, expand to “Spouse name” to capture the name of the spouse
- [x] On the field “Is your household food, socially and economically secure?”. Add an  information icon that will show this information “for example: Able to provide 3 meals per day/ all school-going children enrolled in school; lowest level of education is secondary school; single-headed household; child-headed household; main material of the floor is not earth/sand; Has source of income through stable employment or is engaged in farming/livestock farming etc.). If not, refer to appropriate household economic strengthening program/Government Social Protection program at enrollment” When a user clicks there.
- [x] The field “Is your household food, socially and economically secure” should not be in bold maintain the same style on all the features

### Household profile

- [x] Ensure the Emergency contact name and phone number are prefilled once information  has been provided on enrollment.
- [x]  Last edited and phone number of the case worker should be showing on the profile. To track the case worker who last edited the profile.

### VCA profile

- [x] On VCA screening when the subpopulations have been edited, this should also reflect on the VCA profile. For example if a user select yes to “Children of Female Sex Workers (FSWs)” and later discovers when screening the option selected should be “No”. This change should also reflect on the VCA profile.
- [x] Last edited and phone number of the case worker should be showing on the profile. To track the case worker who last edited the profile.
- [x] Ensure when the user clicks on the phone icon on the profile, the app does not clash.

### Vulnerability Assessment

- [x] The field “Is the VCA on ART?” Should be prefilled, If this information has been captured on “Index VCA screening”.

### Household Register

- [x] Searching for a household is causing the application to crush.
- [x] Household duplication when adding a family member on household profile

### Service Report
- [ ] Currently data is not saving on the Service report
- [ ] It has to be relooked into

### Referrals
- [x] Currently data is not saving on the referral feature
- [x] Can we add date service provided for each service once someone indicates that a service has been provided?

**Comment by Yosefe27** [comment]
@gladysyabs Kindly note that all items on this issue have been resolved except the service report. For us to manage that issue efficiently, and also because the service report issue is currently on hold, kindly create a separate issue for it so that this umbrella issue can be closed. @chobela
