### ISSUE TITLE
Issues opened as of build provided on 04/042022 

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#791]
### VCA Index Register Entry Point
**VCA vulnerability assessment**

- [x] If the subpopulation for the VCA on Index VCA screening is “HEI” so this means on VCA vulnerability, the status should be negative and not positive.

**Add Family Members**

- [x] The field “Ward” should prefill on add family members because this information has been collected already.
- [x] On add family members once the “Date of birth” has been added. The age for that member also shows, similar to how this has been implemented on index VCA screening
- [x] The “Screening Location” should be prefilled, this should pick from the “household screening”, because we are adding this member to the household that we have already screened and at this point we already have captured information on “screening location”.
- [x] The fields “Home address, Nearest Landmark” should prefill because this information has been captured already.
- [x] If the “family member” that we have added is “C/ALHIV” and then we say “Yes” to the question “Was the client eligible for TB Preventive Therapy” the next question “Was client initiated for TB Preventive Therapy” is not showing.

**VCA Case Plan**

- [ ] If a vulnerability has been identified added on the VCA. The button “Vulnerabilities” should immediately show the number “1 Vulnerabilities or 2 Vulnerabilities”. Right now this is not how this is working the user will have to completely close the profile and reopen for this to show.
- [x] When adding a case plan on the field “Date created” if a user enters for example “02/06/2021” It should show the correct quarter “1 st Quarter”  because these users will have to do back data entry at some point.
- [ ] If a vulnerability has been added on the “case plan” of a family member, this needs to be displayed immediately, Currently the user has to click on the back button which is redirecting to show the vulnerabilities added.
- [x] On the domain “HIV Management of HIV+ VCAs” should only show to HIV positive VCAs.

**Referral**

- [ ] Redesign the referral form…You can refer to how tests were implemented on WHO application.
- [x] Add a new field “Provider Phone Number” to capture the contact number for the person who has provided the service.
- [x] Add date service provided for each service once someone indicates that a service has been provided

**Household visitation**

- [x] If the subpopulation for the VCA on Index VCA screening is “HEI” so this means on VCA household visitation, the status should be negative and not positive.
- [x] On the VCA profile change the label on the button “Household visitation” to “Follow-up Visitation”.

**Graduation Assessment**

- [x] If the subpopulation for the VCA on Index VCA screening is “HEI” so this means on VCA Graduation, the status should be negative and not positive.

### Mother Index Register Entry Point

**Mother Index Register**
- [x] The new mother added to the system should be on top of the list unlike on the bottom of the list of mothers displayed.

**Add Mother**

- [x] Change the field label “Plot Number, Village or Street” to “Home Address” For the purpose of consistency.
- [x] Include the field “ART Number”, this should be below the field “Mother’s HIV Status”. ART number should not be a required field.
- [ ] Immediately the Mother has been added, the system should redirect the user to the mother’s profile unlike having the user to search for the mother. The implementation should work the same way as it is working when adding a VCA and household.

**Add Child**

- [x] On adding a biological child once the “Date of birth” has been added. The age for that member also shows, similar to how this has been implemented on index VCA screening.
- [ ] For biological children above the age of 17 who are not HIV positive, they do not qualify to be enrolled into the program. So when adding the biological child if “Yes” is selected on the question “Was the child tested for HIV?”  and “No” is selected on the question “Is the Child/Adolescent HIV positive” and if this child is above the age of 17 then this child does not qualify to be enrolled in the program.

**Household Screening**

- [x] The field “Nearest Landmark” should not be a required field. This should be consistent in the application regardless of the entry point being used.

**Household Profile** 

- [x] When a user opens the household profile from the Mothers profile and fills in information on household screening and enrollment and then saves this information. The button “screen this household” still shows. To see the information on overview  on the household profile the user needs to click on members and view the members profile or close the household profile then reopens it which should not be the case.

**VCA Profile**

- [x] After adding a mother and screening the household, when a user clicks on a profile for the biological child who is in this case a VCA other features do not show apart from VCA screening. The user has to click on the household profile then back to the VCA profile to be able to see the other features.

### Household Register Entry Point
**Household screening**

- [ ] After adding a mother and screening the household, when a user clicks on a profile for the biological child who is in this case a VCA other features do not show apart from VCA screening. The user has to click on the household profile then back to the VCA profile to be able to see the other features.

**Comment by Yosefe27** [comment]
@gladysyabs should Provider Phone number be required on the Referral Form?

**Comment by gladysyabs** [comment]
@Yosefe27 No it should not be a required field

**Comment by chobela** [comment]
@gladysyabs there is no screening location field in Add Family Member Form. See Task 3 under Add Family Members Section.

**Comment by chobela** [comment]
@gladysyabs in the VCA Case plan issue above, Is 02/06/2021 supposed to be First quarter? or 3rd Quarter?

**Comment by gladysyabs** [comment]
@chobela Yes that was first quarter

**Comment by gladysyabs** [comment]
@Yosefe27 I have unticked the "Add a new field “Provider Phone Number” to capture the contact number for the person who has provided the service." because I can not see this field in the last build -11-04-2022
