### ISSUE TITLE
Enrolment on OVC Program: The field for Date when HIV was known is coming as a text field. 

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#82]
![Screenshot_20210827-012318_Ecap II](https://user-images.githubusercontent.com/86519642/131048968-16a12024-ea94-4905-81ba-5215cce7462d.jpg)

The field for Date when HIV was known is coming as a text field.

**Comment by tobiasmakai** [comment]
@gladysyabs close issue if completed and passed the test otherwise move to "To-Do".
