### ISSUE TITLE
Household screening: implement the remaining skip logic that is based on fields completed for each family member.

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#84]
e.g. D1.12 can only appear if the household has registered a member who is male, HIV negative and is aged 15 or above. There are many similar questions that require such skip logic based on sex, hiv status, sub-population, age etc.
![image](https://user-images.githubusercontent.com/25362528/131049885-792cc4b4-2907-4b05-8499-f8e2ef8f8791.png)

**Comment by gladysyabs** [comment]
![Screenshot_20211120-230833_Ecap II](https://user-images.githubusercontent.com/86519642/142740990-0df0f1e2-7f24-4ac5-9ea4-b942d9c5e148.jpg)
This issue has not been worked, If the other household is male, HIV negative and is aged 15 or above. That's when the question on VMMC should appear
