### ISSUE TITLE
Household screening: convert this field to HIV Status with options HIV+, HIV- and Status Unkown so that subsequent fields that depend on the caregiver's HIV status can appropriately show or be skipped.

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#86]
![Screenshot_20210827-020805_Ecap II](https://user-images.githubusercontent.com/25362528/131051927-b6849ef4-76e2-4794-a500-80d9b77a06c4.jpg)

**Comment by gladysyabs** [comment]
label unknown HIV status should be status unknown
